### ISSUE TITLE
Выбор ролей

### ISSUE THREAD

**Issue by Teri-IM** [RushanCources/Project-38#1]
Напишите кому какие предпочтительнее роли. По типу "Мне нуже writer я программист и буду писать код" или "Я тестер и хотя я могу писать едкие комментарии под коммитами и так, но мне нужен triage чтобы писать issue и полноценно ими управлять" или третий вариант "мне надо maintain ибо я готов взять на себя весь груз ответственности за пользовательские настройки репозитория и посильно помогать" и сразу предупрежду в maintain работы много и даже очень, а на первых порах даже больше чем у прогеров

**Comment by Teri-IM** [comment]
что непонятно спрашивайте здесь, в коментариях и сюда же пишите свои хотелки относительно ролей

**Comment by Teri-IM** [comment]
> 

Готово, в субботу покажу какие есть инструменты для работы с гит. А может даже выложу целое issue где это можно будет обсудить

**Comment by d1ffy** [comment]
Хочу быть Девом, мне нужен writer.

**Comment by Teri-IM** [comment]
> Хочу быть Девом, мне нужен writer.

Готово

**Comment by fonarikn** [comment]
Я работаю с доской объявлений и мне нужен writer
