### ISSUE TITLE
Ошибки в коде

### ISSUE THREAD

**Issue by Teri-IM** [RushanCources/Project-38#101]
\templates\projects\project_page.html

```
       files_names = {{files_names | js }}
       update_files_url = '{% url 'update_file' %}'
```

**важность 5/10**

**Comment by Teri-IM** [comment]
`def create_data(request: HttpRequest):
    user1, created = User.objects.get_or_create(username="aaa1", first_name="Надежда", middle_name="Борисовна",
                                                last_name="Тукова", email="a@a.ru", role="Учитель")
    user1.set_password("1")
    user1.save()
    user2, created = User.objects.get_or_create(username="aaa2", first_name="Наталья", middle_name="Львовна",
                                                last_name="Попова", email="a@a.ru",
                                                role="Учитель")
    user2.set_password("1")
    user2.save()
    user3, created = User.objects.get_or_create(username="aaa3", first_name="Алексей", middle_name="Романович",
                                                last_name="Дмитриев", email="a@a.ru",
                                                role="Ученик")
    user3.set_password("1")
    user3.save()
    user4, created = User.objects.get_or_create(username='d1ffy', last_name='Кокорин', first_name='Петр', middle_name='Алексеевич',
                                                email='helpersteam96@inbox.ru', role='Администратор')
    user4.set_password("1")
    user4.save()
    user5, created = User.objects.get_or_create(username='Cbytl', last_name='Кабанин', first_name='Денис', middle_name='Андреевич',
                                                email='email@email.ru', role='Администратор')
    user5.set_password("555555")
    user5.save()
    project = Project.objects.create(name="Проект1", teacher=user1, student=user3)
    project.set_subject("Математика")
    project.save()
    return HttpResponse("Всё ок")`
??????????????????????

**Comment by Teri-IM** [comment]
![изображение](https://github.com/RushanCources/Project-38/assets/63192118/0369ecb3-e351-473f-9e34-e6fd6ef93663)
Зачем?

**Comment by AdLeGeR** [comment]
заполнение бд

**Comment by AdLeGeR** [comment]
Чтобы не создавать каждого нового пользователя вручную

**Comment by AdLeGeR** [comment]
а в первом что не так?
