### ISSUE TITLE
При отображении текста в проектах теряется табуляция

### ISSUE THREAD

**Issue by Teri-IM** [RushanCources/Project-38#124]
_Баг был получен на [Issue118_project-ui](https://github.com/RushanCources/Project-38/tree/issue118_project-ui)_
Как воспроизвести баг
Переходим в любую ветку с рабочим редактором проекта
Берём любой текст с наличием        больших отступов

Пустых строк
Или просто пере-
носов
И меняем/вводим его в описании проекта
Получаем текст без отступов
![изображение](https://github.com/RushanCources/Project-38/assets/63192118/5e87ce7e-c1fe-4a85-a997-36c40208fafd)
![изображение](https://github.com/RushanCources/Project-38/assets/63192118/b855e2d2-0c06-49e3-9758-9ea686699647)

**Comment by cbytl1** [comment]
Это нужно, чтобы не было переизбытка пробелов и пустых строк. Так что делается это специально
