### ISSUE TITLE
Can we fix it? 

### ISSUE THREAD

**Issue by Teri-IM** [RushanCources/Project-38#125]
Можем ли мы починить появление этого уведомления?
![изображение](https://github.com/RushanCources/Project-38/assets/63192118/a82e6cfd-f158-4627-84fa-99b7d86b2dd3)

**Comment by cbytl1** [comment]
я там добавлял это для ошибок и они работают, но походу сюда ещё прилетают уведомления с регистрации 
@AdLeGeR посмотри там, потому что я не знаю как это решить, а ради пару буковок отправлять пользователя на другую страницу (страницу ошибки) не хочется

**Comment by AdLeGeR** [comment]
Нужно добавить дополнительный If в цикле отрисовки сообщений

```
<div class="errors">
        {% if messages %}
        {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} 
        <p class="error">{{ message }}</p> 
        {% endif %}
        {% endfor %}
        {% endif %}
</div>
```

**Comment by AdLeGeR** [comment]
А вообще, первый uf лишний. И без него всё работает
