### ISSUE TITLE
Реализация ui для проекта на этапе работы

### ISSUE THREAD

**Issue by cbytl1** [RushanCources/Project-38#126]
нужно реализовать desktop ui для страницы проекта на этапе работы. Реализовать как для ученика, так и для учителя

**Comment by Teri-IM** [comment]
Немножко насрал(добавил изменения в дизайне announcemnts) в эту ветку, больше не буду

**Comment by cbytl1** [comment]
Мы с Лешей реализовали страницу проекта на этапе ow_work. Была проделана большая работа. На данный момент по моему мнению это самая проработанная страница. После принятия заявки, к проекта можно будет:
- менять название
- выбирать тип проекта
- выбирать до 3-х абсолютно любых областей
- добавить описание проблемы, актуальности, цели, задач и ожидаемых результатов
- добавить основные файлы (реферат, презентация, защита)
- добавить прочие файлы

А также:
- каждый файл можно прокомментировать, посмотреть предыдущую версию
- основные файлы можно обновлять
- прочие файлы можно удалять
- у каждого раздела есть работающие текстовые подсказки
- реализовано первичное знакомство с каждым блоком путем поэтапного открытия каждого раздела
- реализовано система проверки заполненности каждого блока
