### ISSUE TITLE
Создание модели проекта, учителя, ученика, заявки.

### ISSUE THREAD

**Issue by AdLeGeR** [RushanCources/Project-38#13]
Создание модели проекта, учителя, ученика, заявки.
Необходимо создать вышеперечисленные модели. некоторые из них находятся на стыке приложений управления проектами и администрирования. Нужно договориться о их реализации.
Связанные требования: MP-F-1, MP-F-11, MP-F-3, MP-F-4, ADM-F1, ADM-F2.

**Comment by AdLeGeR** [comment]
промежуточные изменения выложены на бранч

**Comment by Teri-IM** [comment]
как так получилось что запрос на слияние с 16 issue появился раньше?
(я его кстати одобрил)
