### ISSUE TITLE
Переписать предметные области в projects

### ISSUE THREAD

**Issue by AdLeGeR** [RushanCources/Project-38#140]
Сейчас предметные области - это захардкоженый список, нужно это исправить, использовать таблицу с предметными областями

**Comment by cbytl1** [comment]
перед этим тогда надо в базу добавить какой-то минимум предметных областей. После добавления минимума я бы добавлял каждый следующий предмет в базу только если с ним создали тему, где  он главный предмет или этот предмет есть в как минимум 3-х проектах

**Comment by AdLeGeR** [comment]
Я предлагаю сделать по-другому: ограничить пользователей стандартным набором предметов, и, если какого-то предмета на будет хватать, то пользователи пишут на почту поддержки с просьбой добавить предмет, или сделать отдельную страницу для подачи заявок на добавление предмета

**Comment by cbytl1** [comment]
Это слишком запарно, как по мне легче реализовать мой вариант

**Comment by AdLeGeR** [comment]
В твоём варианте есть возможность для создания дубликатов предметов.

**Comment by AdLeGeR** [comment]
Мне кажется, что добавлять предметы нам не придётся, т.к у нас и так очень большой список предметов

**Comment by AdLeGeR** [comment]
["Математика", "Алгебра", "Геометрия", "Теория вероятностей и статистика", "Информатика",
                           "География", "Биология", "Физика",
                           "Химия", "Основы безопасности жизнедеятельности", "Естествознание", "Экология", "Астрономия",
                           "История", "Обществознание",
                           "Экономика", "Право", "Разговоры о важном", "Краеведение",
                           "Основы религиозных культур и светской этики", "Родная литература",
                           "Русский язык", "Литература", "Иностранный язык(Английский)", "Иностранный язык(Французский)",
                           "Иностранный язык(Немецкий)",
                           "Труд", "Технология", "Черчение", "Индивидуальный проект", "Физическая культура", "Музыка",
                           "Изобразительное искусство",
                           "Другая научная область/предмет"]
