### ISSUE TITLE
ui для редактирования объявлений

### ISSUE THREAD

**Issue by cbytl1** [RushanCources/Project-38#145]
Сделать похожий ui для редактирования объявлений, какой сейчас у создания объявлений

**Comment by cbytl1** [comment]
на данный момент реализована большая часть. Теперь жду, когда будет готов бэк, чтобы уже мог доделать до конца

**Comment by happyzxzxz** [comment]
Бэк готов

**Comment by cbytl1** [comment]
> Бэк готов

Я сегодня тогда доделаю редактирование

**Comment by cbytl1** [comment]
ui обновлен
