### ISSUE TITLE
Работа над отделом проектов

### ISSUE THREAD

**Issue by cbytl1** [RushanCources/Project-38#147]
Переделать форму подачи заявки в месте выбора учителей и выбора предметов
Переделать отображение проектов
Добавить возможность завершения проекта
Добавить возможность просмотра завершенных проектов
Исправить баги

**Comment by AdLeGeR** [comment]
На текущий момент переделано только отображение проектов и пофикшены баги

**Comment by cbytl1** [comment]
возможность завершения проекта и просмотра завершенного проекта также есть. Осталось доделать форму подачи заявки

**Comment by cbytl1** [comment]
все сделано, возможно позже обнаружатся баги, но тогда поправим
