### ISSUE TITLE
Баг с появляющимся popup

### ISSUE THREAD

**Issue by Kostyahard222** [RushanCources/Project-38#167]
![image](https://github.com/RushanCources/Project-38/assets/84705935/e0d8eafa-da97-4776-8370-50be9d0acaac)
Аккаунт успешно создан
при взятии проекта из тем

**Comment by AdLeGeR** [comment]
это пофикшено, но не в мейне. https://github.com/RushanCources/Project-38/issues/125

**Comment by AdLeGeR** [comment]
dublicate #125

**Comment by AdLeGeR** [comment]
Duplicate of #125
