### ISSUE TITLE
Дизайн

### ISSUE THREAD

**Issue by Teri-IM** [RushanCources/Project-38#22]
Здесь будут обсуждения по поводу дизайна.
Когда у тебя возникает вопрос: А почему на _your_page_ нет какого-то элемента, ты идёшь **сюда**
Когда ты видишь как **страница/элемент/разметка** выглядит не так как выглядит нормальная **страница/элемент/разметка** ты идёшь **сюда**
Когда ты хочешь помочь людям закрыть сращивание струн(Pull-request) ты идёшь **сюда**
Когда тебе нужно или ты уже созда(ть)л стили и анимации к какой-либо части сайта ты ид... ну вы поняли

**Comment by Teri-IM** [comment]
пошаманил над гридами и стилями в html/testgrid #2f9d9461ddf33a13fb350adc271108a671231644

**Comment by Teri-IM** [comment]
Проведу слияние струн main и Design Features ибо важный функционал мы не трогали а комитов после последнего слияния накопилось прилично

**Comment by Teri-IM** [comment]
> Проведу слияние струн main и Design Features ибо важный функционал мы не трогали а комитов после последнего слияния накопилось прилично

Провел, спасибо за ревью @cbytl1

**Comment by Teri-IM** [comment]
_Итак_ 
у нас есть [макеты](https://github.com/RushanCources/Project-38/issues/34)
и [вёрстка](https://github.com/RushanCources/Project-38/issues/32) по ним

**Comment by Teri-IM** [comment]
Есть предложение со временем на главной странице реализовать заметки. Чтоб каждый заходя на главную видел то что сам записал.

**Comment by cbytl1** [comment]
можно попробовать. Думаю сделать будет не очень трудно. Нужно в принципе обсудить наполнение главной страницы. Ведь главная страница, ну она типо главная, там по идее довольно много инфы должно быть и разных блоков
