### ISSUE TITLE
Отправка заявки на проект

### ISSUE THREAD

**Issue by XameleonchikGreen** [RushanCources/Project-38#27]
Фронтэнд отправки заявки на проект с внесением в базу данных

**Comment by Teri-IM** [comment]
Бек сделаешь ты? И нужны ли ещё какие кнопки или может, особенности дизайна. Там выпадающая менюшка какая или значки?

**Comment by XameleonchikGreen** [comment]
Смотря что ты имеешь в виду под бэком. По кнопкам - из базовой страницы переходим в раздел "Проекты" и там уже я поработал (пока не пушил сюда). Дизайн, я думаю, можно будет адаптировать из основной страницы, но нужно, чтобы его кто-то сделал. Пока рисую в базовом дизайне

**Comment by Teri-IM** [comment]
> Бек сделаешь ты? И нужны ли ещё какие кнопки или может, особенности дизайна. Там выпадающая менюшка какая или значки?

Как будет время закину наброски

**Comment by Teri-IM** [comment]
> Смотря что ты имеешь в виду под бэком. По кнопкам - из базовой страницы переходим в раздел "Проекты" и там уже я поработал (пока не пушил сюда). Дизайн, я думаю, можно будет адаптировать из основной страницы, но нужно, чтобы его кто-то сделал. Пока рисую в базовом дизайне html

Я могу скинуть тебе наработки тогда либо адаптировать как тебе надо, потом сверстаю. Но с тобой гдет списаться тогда надо, а лучше в войс

**Comment by XameleonchikGreen** [comment]
Можно в телеграмм - @xameleonchik

**Comment by AdLeGeR** [comment]
я сделал бэк

**Comment by AdLeGeR** [comment]
Я реализовал выбор учителей с помощью выпадающего списка. Неплохо бы сделать поиск в этом списке, но так как html и js я не знаю, то надо, что бы это сделал кто-то другой
