### ISSUE TITLE
Страница с темами проектов

### ISSUE THREAD

**Issue by Lexi-Wooo** [RushanCources/Project-38#29]
Требования для страницы с темами

**Comment by Lexi-Wooo** [comment]
![Требования](https://user-images.githubusercontent.com/125133234/221682268-47268c85-e67f-4f33-af6c-f7d00e763d6e.jpg)

**Comment by Lexi-Wooo** [comment]
Сделал модель темы, загрузил в бд

**Comment by cbytl1** [comment]
Доделал макет списка. Находится на бранче [issue25_admin_menu_creation](https://github.com/RushanCources/Project-38/tree/issue25_admin_menu_creation). Как я понял поле для подачи заявки на создание темы делает @Teri-IM. 

Внешне desktop версия вполне готова. Возможно есть мелкие косяки, но если что поправлю.

Осталось только наполнить макет и приделать к нему функционал. И сделать поле для подачи заявки конечно же.

**Comment by Lexi-Wooo** [comment]
Изменил навигацию через совокупность subjects/urls.py
