### ISSUE TITLE
announcements_board (aka dec)

### ISSUE THREAD

**Issue by Teri-IM** [RushanCources/Project-38#36]
Как вижу эта ветка уже есть. Значит разметку скину сюда

**Comment by Teri-IM** [comment]
Ветка малость устарела...
В ней даже нет static
надо будет провести слияние поскорее и открыть новую ветку

**Comment by Teri-IM** [comment]
Слияние провели, ui добавили всё работает
[коммит](https://github.com/RushanCources/Project-38/commit/3072ad2ec52b9322c186cdf360eb29c078542dd9)
сразу после этого пара хотфиксов от @happyzxzxz

**Comment by Teri-IM** [comment]
Кто-то влез в ui _(руки ему оторвать)_ и закомитил сломанный вариант
Всё починил и изменил адаптив под новый макет (если надо изменить ещё сильнее напишите мне а не лезьте в код)
+ обновил структуру кода до уровня admin_menu

**Comment by Teri-IM** [comment]
Дальше нужно создать структуру объявления и добавить их отображение через js и bd
jsдля подгрузки, bd для хранения

**Comment by Teri-IM** [comment]
Макет редактирования есть, _даже два_ 
Нужно определить будем ли мы создавать объявление на новой странице или всплывающим окном

**Comment by happyzxzxz** [comment]
НЛ просила всплывающим окном

**Comment by Teri-IM** [comment]
Круто, уже так и делаю

**Comment by Teri-IM** [comment]
> НЛ просила всплывающим окном

Это будет сложно, пока сделаем страничкой. А там может переделаем

**Comment by cbytl1** [comment]
Я думаю, что можно будет сделать также, как реализовали функционал редактирования пользователя на странице администрации. Форма для редактирования одна, просто при нажатии на кнопку редактирования у какого-либо элемента эта единственная форма появляется и туда заносятся данные объявления через js
