### ISSUE TITLE
Починка ссылок между страницами и проч.

### ISSUE THREAD

**Issue by Teri-IM** [RushanCources/Project-38#44]
Между страницами сломаны некоторые переходы, а также у нас пустая home.html

**Comment by cbytl1** [comment]
home.html у нас пустой для авторизованных пользователей. Для этого нужно для начала разработать макет главной страницы. Там по сути должен быть блок по твоему проекту, может блок новостей ну и ещё что-нибудь по мелочи. На самом деле особо не знаю что туда добавить

**Comment by Teri-IM** [comment]
> home.html у нас пустой для авторизованных пользователей. Для этого нужно для начала разработать макет главной страницы. Там по сути должен быть блок по твоему проекту, может блок новостей ну и ещё что-нибудь по мелочи. На самом деле особо не знаю что туда добавить

как сделаешь base.html можно будет его туда вставить а так спросим завтра

**Comment by cbytl1** [comment]
если нужны ссылки для каких-то переходов то в атрибут href вставляй вот это:

Главная - {% url 'home' %}
Профиль - {% url 'profile' %}
Список тем - {% url 'theme_list' %}
Админка - {% url 'admin_menu' %}
Окно входа - {% url 'login' %}
Окно токена - {% url 'token_page' %}
Окно регистрации - {% url 'register' %}

Я так понимаю, что уже добавились и другие страницы по типу объявлений, создание темы проекта и тд. Я сейчас посмотрю, что появилось и тоже добавлю к ним ссылки
