### ISSUE TITLE
Разработка визуала профиля учителя

### ISSUE THREAD

**Issue by cbytl1** [RushanCources/Project-38#59]
Необходимо реализовать визуал профиля для пользователя с ролью "Учитель"

**Comment by AdLeGeR** [comment]
Можно ли добавить в профиль учителя такие кнопки как: 
1. Просмотр заявок (переводит или открывает (или просто показывает) список заявок на проект, где у каждой заявки есть: 
   1. кнопка одобрить
   2. кнопка отклонить
   3. название проекта
   4. ученик, приславший проект
2. Кнопка "Прекратить получать заявки"

**Comment by cbytl1** [comment]
В профиле учителя  есть три вкладки:
-текущие проекты
-заявки на новые проекты
-проекты прошлых лет
Это три разных списка и каждый элемент списка(т.е проект) можно раскрыть для просмотра деталей. Если в заявках на новый проект будет только название, краткое описание, предметная область и возможно что-нибудь ещё по мелочи(мб файлы какие-нибудь), то в текущих проектах и в проектах прошлых лет можно будет как минимум увидеть название, проблему, актуальность, цель, задачи, предполагаемые результаты проекта, предметная область, ноу это или проект, файлы с презентацией и защитой проекта. Мб что-то ещё можно будет добавить. У текущих проектов также будут кнопки для завершения проекта, у заявок кнопки отклонить или принять проект, а у проектов прошлых лет будет год работы и мб награды, которые получил ученик за данный проект/ноу
