### ISSUE TITLE
Создать простейшую навигацию в проекте

### ISSUE THREAD

**Issue by rushanrr** [RushanCources/Project-38#6]
Создать простейшую навигацию в проекте.
Необходимо иметь возможность переключаться между страницами:
1 - projects
2 - announcements
3 - subjects
4 - management

требования: CMN-F-1, CMN-F-2, CMN-F-3, CMN-F-4, CMN-F-5,

**Comment by AdLeGeR** [comment]
Я сделал это
[liceum38.zip](https://github.com/RushanCources/Project-38/files/10049790/liceum38.zip)

**Comment by rushanrr** [comment]
Change reviewed and merged with pull request [12](https://github.com/RushanCources/Project-38/pull/12)
