### ISSUE TITLE
Создание темы и ее редактирование

### ISSUE THREAD

**Issue by Lexi-Wooo** [RushanCources/Project-38#73]
- сделать возможность создания темы
- сделать ui под страницу с созданием темы
- связать фронтэнд с бэкэндом
- сделать возможность для редактирования темы под ui создания темы
- связать фронтэнд и бэкэнд
- сделать merge с отлаживанием конфликтов в issue63_theme-list-create

**Comment by cbytl1** [comment]
Реализовал ui для создания списка тем на своем бранче [issue70_theme-list-creation_ui](https://github.com/RushanCources/Project-38/tree/issue70_theme-list-creation_ui)
