### ISSUE TITLE
File not found issue on server

### ISSUE THREAD

**Issue by rushanrr** [RushanCources/Project-38#97]
Application fails to start on server with error:
FileNotFound: No such file or directory 'static/img/announcements/covers'

Looks like path could not be resolved as location of static files based on STATIC_ROOT property.
STATIC_ROOT = "/home/host1859562/host1859562.hostland.pro/htdocs/www/static"

**Comment by rushanrr** [comment]
I've created branch "issue-97_temp_fix_for_file_not_found" with temporary change. It should be removed after the proper fix.

**Comment by Teri-IM** [comment]
Ветка с фиксом слита и закрыта
